# app.py
# Streamlit MVP app for the Blackjack AI Assistant
#
# This app connects:
# - blackjack_engine.py for the recommendation
# - optional nanoGPT model output for explanation text
#
# To run:
#   streamlit run app.py
#
# Optional files used:
# - blackjack_engine.py
# - model.py
# - out/best_model.pt
# - out/meta.json

import json
from pathlib import Path

import streamlit as st
import torch

from blackjack_engine import recommend_action, format_for_gpt
from model import GPT, GPTConfig


# --------------------------------------------------
# Page config
# --------------------------------------------------
st.set_page_config(
    page_title="Blackjack AI Assistant",
    page_icon="🃏",
    layout="centered",
)

st.title("🃏 Blackjack AI Assistant")
st.write(
    "Get a real-time blackjack recommendation for a two-deck game, "
    "plus an explanation generated by a rules engine and an optional nanoGPT model."
)


# --------------------------------------------------
# Helpers
# --------------------------------------------------
VALID_CARDS = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"]


def normalize_for_display(cards):
    return ",".join(cards)


def load_gpt_model(checkpoint_path="out/best_model.pt", meta_path="out/meta.json"):
    """
    Load trained nanoGPT model and tokenizer metadata.
    Returns:
        model, stoi, itos, device
    or:
        None, None, None, None
    """
    ckpt_file = Path(checkpoint_path)
    meta_file = Path(meta_path)

    if not ckpt_file.exists() or not meta_file.exists():
        return None, None, None, None

    device = "cuda" if torch.cuda.is_available() else "cpu"

    with open(meta_file, "r", encoding="utf-8") as f:
        meta = json.load(f)

    stoi = meta["stoi"]
    itos = {int(k): v for k, v in meta["itos"].items()}

    checkpoint = torch.load(ckpt_file, map_location=device)
    config = GPTConfig(**checkpoint["model_args"])
    model = GPT(config).to(device)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    return model, stoi, itos, device


def encode_text(text, stoi):
    return [stoi[c] for c in text]


def decode_tokens(tokens, itos):
    return "".join([itos[i] for i in tokens])


def generate_gpt_explanation(prompt, max_new_tokens=100, temperature=0.8, top_k=30):
    """
    Generate explanation text from the trained nanoGPT model if available.
    Falls back to None if model/tokenizer are unavailable or prompt has unseen chars.
    """
    model, stoi, itos, device = load_gpt_model()
    if model is None:
        return None

    try:
        x = torch.tensor([encode_text(prompt, stoi)], dtype=torch.long, device=device)
    except KeyError:
        return None

    with torch.no_grad():
        y = model.generate(
            x,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            top_k=top_k,
        )

    return decode_tokens(y[0].tolist(), itos)


def extract_reason_only(generated_text):
    """
    Tries to shorten GPT output to the most useful explanation.
    """
    if generated_text is None:
        return None

    if "Reason:" in generated_text:
        return generated_text.split("Reason:", 1)[-1].strip()

    return generated_text.strip()


# --------------------------------------------------
# Sidebar
# --------------------------------------------------
st.sidebar.header("Game Settings")
can_double = st.sidebar.checkbox("Double allowed", value=True)
can_split = st.sidebar.checkbox("Split allowed", value=True)
dealer_hits_soft_17 = st.sidebar.checkbox("Dealer hits soft 17", value=False)

use_gpt = st.sidebar.checkbox("Use trained nanoGPT explanation (if available)", value=True)

st.sidebar.markdown("---")
st.sidebar.write("Recommended training checkpoint paths:")
st.sidebar.code("out/best_model.pt\nout/meta.json")


# --------------------------------------------------
# Input form
# --------------------------------------------------
st.subheader("Enter the current hand")

col1, col2, col3 = st.columns(3)

with col1:
    player_card_1 = st.selectbox("Player Card 1", VALID_CARDS, index=7)  # 8
with col2:
    player_card_2 = st.selectbox("Player Card 2", VALID_CARDS, index=7)  # 8
with col3:
    dealer_card = st.selectbox("Dealer Upcard", VALID_CARDS, index=4)  # 5

additional_cards_input = st.text_input(
    "Additional player cards (optional, comma-separated, e.g. 5,3)",
    value="",
    help="Use this if the player already hit and has more than two cards.",
)

analyze_button = st.button("Analyze Hand")


# --------------------------------------------------
# Main analysis
# --------------------------------------------------
if analyze_button:
    try:
        player_cards = [player_card_1, player_card_2]

        if additional_cards_input.strip():
            extras = [c.strip().upper() for c in additional_cards_input.split(",") if c.strip()]
            player_cards.extend(extras)

        result = recommend_action(
            player_cards=player_cards,
            dealer_card=dealer_card,
            can_double=can_double,
            can_split=can_split,
            dealer_hits_soft_17=dealer_hits_soft_17,
            deck_count=2,
        )

        st.markdown("---")
        st.subheader("Recommendation")

        action = result["recommended_action"]
        confidence = result["confidence"]
        explanation = result["explanation"]

        metric_col1, metric_col2, metric_col3 = st.columns(3)
        metric_col1.metric("Recommended Action", action)
        metric_col2.metric("Confidence", f"{confidence:.2f}")
        metric_col3.metric("Player Total", result["hand_info"]["total"])

        hand_type_parts = []
        if result["hand_info"]["is_soft"]:
            hand_type_parts.append("Soft")
        else:
            hand_type_parts.append("Hard")

        if result["hand_info"]["is_pair"]:
            hand_type_parts.append("Pair")

        if result["hand_info"]["is_blackjack"]:
            hand_type_parts.append("Blackjack")

        st.write(f"**Player Cards:** {normalize_for_display(result['state']['player_cards'])}")
        st.write(f"**Dealer Upcard:** {result['state']['dealer_card']}")
        st.write(f"**Hand Type:** {' / '.join(hand_type_parts)}")

        st.markdown("### Rules Engine Explanation")
        st.info(explanation)

        gpt_prompt = format_for_gpt(result)

        st.markdown("### Structured Prompt Sent to GPT")
        st.code(gpt_prompt)

        if use_gpt:
            gpt_output = generate_gpt_explanation(
                prompt=gpt_prompt,
                max_new_tokens=120,
                temperature=0.8,
                top_k=30,
            )

            st.markdown("### nanoGPT Explanation")
            if gpt_output is None:
                st.warning(
                    "No trained nanoGPT checkpoint was found, or the prompt contains characters "
                    "not included in the training tokenizer. Using the rules-based explanation only."
                )
            else:
                cleaned = extract_reason_only(gpt_output)
                st.success(cleaned)

                with st.expander("Show full nanoGPT output"):
                    st.code(gpt_output)

        st.markdown("---")
        st.subheader("Raw Engine Output")
        st.json(result)

    except Exception as e:
        st.error(f"Error: {e}")


# --------------------------------------------------
# Footer / instructions
# --------------------------------------------------
st.markdown("---")
st.subheader("How this MVP works")
st.write(
    "This app uses a hybrid design: a blackjack rules engine computes the recommended move, "
    "and a trained nanoGPT model can optionally turn that result into a natural-language explanation."
)

with st.expander("Example test hands"):
    st.write("Try these:")
    st.code(
        "Player: 8,8 | Dealer: 6\n"
        "Player: 10,6 | Dealer: 7\n"
        "Player: A,7 | Dealer: 9\n"
        "Player: 5,5 | Dealer: 6"
    )

with st.expander("Project file checklist"):
    st.code(
        "model.py\n"
        "train.py\n"
        "sample.py\n"
        "blackjack_engine.py\n"
        "app.py\n"
        "data/train.txt\n"
        "out/best_model.pt\n"
        "out/meta.json"
    )
